In [1]:
import pandas as pd
import numpy as np

In [2]:
pip install kaggle

Requirement already satisfied: kaggle in f:\lib\site-packages (1.7.4.5)
Requirement already satisfied: bleach in f:\lib\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in f:\lib\site-packages (from kaggle) (2025.10.5)
Requirement already satisfied: charset-normalizer in f:\lib\site-packages (from kaggle) (3.4.3)
Requirement already satisfied: idna in f:\lib\site-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in f:\lib\site-packages (from kaggle) (6.32.1)
Requirement already satisfied: python-dateutil>=2.5.3 in f:\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in f:\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in f:\lib\site-packages (from kaggle) (2.32.5)
Requirement already satisfied: setuptools>=21.0.0 in f:\lib\site-packages (from kaggle) (80.9.0)
Requirement already satisfied: six>=1.10 in f:\lib\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in f:\lib\site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in f:\lib\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in f:\lib\site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in f:\lib\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: colorama in f:\lib\site-packages (from tqdm->kaggle) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install kagglehub

Requirement already satisfied: kagglehub in f:\lib\site-packages (0.3.13)
Requirement already satisfied: packaging in f:\lib\site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in f:\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in f:\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in f:\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in f:\lib\site-packages (from requests->kagglehub) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in f:\lib\site-packages (from requests->kagglehub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\lib\site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in f:\lib\site-packages (from requests->kagglehub) (2025.10.5)
Requirement already satisfied: colorama in f:\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import kagglehub
path = kagglehub.dataset_download("shilongzhuang/telecom-customer-churn-by-maven-analytics")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\Abdulah\.cache\kagglehub\datasets\shilongzhuang\telecom-customer-churn-by-maven-analytics\versions\1

In [14]:
path = r'C:\Users\Abdulah\OneDrive\7 Semester\pandas\Telecom CCP\telecom_customer_churn.csv'

In [15]:
df = pd.read_csv(path)

In [16]:
df.head(10)

,Customer ID,Gender,Age,Married,Number of Dependents,City,Zip Code,Latitude,Longitude,Number of Referrals,...,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Customer Status,Churn Category,Churn Reason
0,0002-ORFBO,Female,37,Yes,0,Frazier Park,93225,34.827662,-118.999073,2,...,Credit Card,65.60,593.30,0.00,0,381.51,974.81,Stayed,NaN,NaN
1,0003-MKNFE,Male,46,No,0,Glendale,91206,34.162515,-118.203869,0,...,Credit Card,-4.00,542.40,38.33,10,96.21,610.28,Stayed,NaN,NaN
2,0004-TLHLJ,Male,50,No,0,Costa Mesa,92627,33.645672,-117.922613,0,...,Bank Withdrawal,73.90,280.85,0.00,0,134.60,415.45,Churned,Competitor,Competitor had better devices
3,0011-IGKFF,Male,78,Yes,0,Martinez,94553,38.014457,-122.115432,1,...,Bank Withdrawal,98.00,1237.85,0.00,0,361.66,1599.51,Churned,Dissatisfaction,Product dissatisfaction
4,0013-EXCHZ,Female,75,Yes,0,Camarillo,93010,34.227846,-119.079903,3,...,Credit Card,83.90,267.40,0.00,0,22.14,289.54,Churned,Dissatisfaction,Network reliability
5,0013-MHZWF,Female,23,No,3,Midpines,95345,37.581496,-119.972762,0,...,Credit Card,69.40,571.45,0.00,0,150.93,722.38,Stayed,NaN,NaN
6,0013-SMEOE,Female,67,Yes,0,Lompoc,93437,34.757477,-120.550507,1,...,Bank Withdrawal,109.70,7904.25,0.00,0,707.16,8611.41,Stayed,NaN,NaN
7,0014-BMAQU,Male,52,Yes,0,Napa,94558,38.489789,-122.270110,8,...,Credit Card,84.65,5377.80,0.00,20,816.48,6214.28,Stayed,NaN,NaN
8,0015-UOCOJ,Female,68,No,0,Simi Valley,93063,34.296813,-118.685703,0,...,Bank Withdrawal,48.20,340.35,0.00,0,73.71,414.06,Stayed,NaN,NaN
9,0016-QLJIS,Female,43,Yes,1,Sheridan,95681,38.984756,-121.345074,3,...,Credit Card,90.45,5957.90,0.00,0,1849.90,7807.80,Stayed,NaN,NaN